apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app-stable
        image: germanx/app:90
        lifecycle:
          preStop:
            exec:
              command: ["sleep","20"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        - name: OK_PERCENT
          value: "0.90"
        - name: DELAY_SEC
          value: "1"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      terminationGracePeriodSeconds: 120
  strategy:
    canary:
      analysis:
        startingStep: 1
        templates:
        - templateName: fail-rate
      steps:
      - setWeight: 25
      - pause: {duration: 60s}
      - setWeight: 50
      - pause: {duration: 60s}
      - setWeight: 75
      - pause: {duration: 60s}
